; Generated by llvm-security-parser
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

define i32 @check_password(i32 %input) {
  %1 = alloca i32, align 4
  %2 = alloca i32, align 4
  store i32 %input, i32* %2, align 4
  %3 = alloca i32, align 4
  %4 = add i32 0, 1234
  store i32 %4, i32* %3, align 4
  %5 = load i32, i32* %2, align 4
  %6 = load i32, i32* %3, align 4
  %7 = icmp eq i32 %5, %6
  br i1 %7, label %8, label %9

8:
  %8 = add i32 0, 1
  store i32 %8, i32* %1, align 4
  br label %10

10:
  %9 = load i32, i32* %1, align 4
  ret i32 %9
9:
  %10 = add i32 0, 0
  store i32 %10, i32* %1, align 4
  br label %11

11:
  %11 = load i32, i32* %1, align 4
  ret i32 %11
}

